### ISSUE TITLE
POSIX style arguments

### ISSUE THREAD

**Issue by Goreek** [Gameslinger/rust-stereogram#1]
I like the project very much (stereograms are really underrated), and I'm also learning Rust.

I suggest to implement POSIX style CLI arguments for the utility. Obvious proposal is:

>  --depth-source, -d   Image file name that represent depth distribution.
>  --pattern-size, -p Size of repeating dots pattern square (in pixels)
>  --shift-amplitude, -s Amplitude of distortion of repeating pattern to represent depth (0.1 to 0.9)
>  --width, -w  Width of outer image (in pixels)
>  --height, -h  Height of outer image (in pixels)    
>  --out,-o Stereogram output image file name 

So utility will be called
`./autostereogram --depth-source=shark.png --pattern-size=40 --shift-amplitude=0.6 --width=600 --height=400 --out=shark-stereogram.png`

All parameters except --depth-source and --out can be ommitted, with default value applied.
For --width and --height default value should be just the same size as original depth image.

I can do it, if you assign the task on me.

**Comment by Gameslinger** [comment]
I'm glad you like the project! That is a great idea and improvement. I assigned you to the issue. Have fun!

**Comment by Goreek** [comment]
It looks like I don't have permissions to create a branch for the issue.
Please, provide it to me or create the branch **posix-cli-args** at the right panel in Development section.

**Comment by Gameslinger** [comment]
Thank you for your patience. Hopefully, you are able to contribute now.

**Comment by Goreek** [comment]
Hmmm, I suppose I still can't contribute until you give me such permission for the repository.

> ~\projects\repo\rust-stereogram>git push
> remote: Permission to Gameslinger/rust-stereogram.git denied to Goreek.

Please try to add me at the \<Repository main page\> -> Settings ->Collaborators

**Comment by Goreek** [comment]
I accepted you invitation, and now I can submit. Thank you!

**Comment by Gameslinger** [comment]
Glad we got that figured out! Thanks for contributing!
